=== LucaMorazzano/XML-Rappresentativo/telefoni.dtd
<!ELEMENT telefoni (telefono+)>
          <!ELEMENT telefono (modello,prezzo,componenti)>
                    <!ATTLIST telefono
                                    id  CDATA #REQUIRED
                                    stato (IT|US|EN|FR|GR|CH) "IT"
                                    os (IOS|Android) "IOS"
                      >
                      
                      <!ELEMENT modello ( nome , annoproduzione )>
                            <!ELEMENT nome (#PCDATA)>
                            <!ELEMENT annoproduzione (#PCDATA)>
                            
                      <!ELEMENT prezzo (#PCDATA)>
                      
                      <!ELEMENT componenti (processore, schedagrafica, ram, schedarete, display)>
                            <!ELEMENT processore (nome, frequenza)>
                                            <!ELEMENT frequenza (#PCDATA)>
                                            
                            <!ELEMENT schedagrafica (nome, vram)>
                                          <!ELEMENT vram (#PCDATA)>
                                          
                            <!ELEMENT ram (nome,quantita)>
                                          <!ELEMENT quantita (#PCDATA)>
                            
                            <!ELEMENT schedarete (nome)>
                                      <!ATTLIST schedarete 
                                             tecnologia (3G|4G|5G) "4G"
											 >
                                    
                            <!ELEMENT display (dimensioni)>
                                    <!ELEMENT dimensioni (#PCDATA)>
                                    <!ATTLIST display  tipologia (OLED|AMOLED|IPS) "IPS">

=== LucaMorazzano/XML-Rappresentativo/telefoni.xml
<?xml version="1.0" encoding= "UTF-8"?>
<!DOCTYPE telefoni SYSTEM "telefoni.dtd" >
<!--<!DOCTYPE telefoni[
<!ELEMENT telefoni (telefono+)>
          <!ELEMENT telefono (modello,prezzo,componenti)>
                    <!ATTLIST telefono
                                    id  CDATA #REQUIRED
                                    stato (IT|US|EN|FR|GR|CH) "IT"
                                    os (IOS|Android) "IOS"
                      >
                      
                      <!ELEMENT modello ( nome , annoproduzione )>
                            <!ELEMENT nome (#PCDATA)>
                            <!ELEMENT annoproduzione (#PCDATA)>
                            
                      <!ELEMENT prezzo (#PCDATA)>
                      
                      <!ELEMENT componenti (processore, schedagrafica, ram, schedarete, display)>
                            <!ELEMENT processore (nome, frequenza)>
                                            <!ELEMENT frequenza (#PCDATA)>
                                            
                            <!ELEMENT schedagrafica (nome, vram)>
                                          <!ELEMENT vram (#PCDATA)>
                                          
                            <!ELEMENT ram (nome,quantita)>
                                          <!ELEMENT quantita (#PCDATA)>
                            
                            <!ELEMENT schedarete (nome)>
                                      <!ATTLIST schedarete 
                                             tecnologia (3G|4G|5G) "4G"
											 >
                                    
                            <!ELEMENT display (dimensioni)>
                                    <!ELEMENT dimensioni (#PCDATA)>
                                    <!ATTLIST display 
									    tipologia (OLED|AMOLED|IPS) "IPS">
					] > -->
              
                                
<telefoni>
	<telefono id="145" stato="IT" os= "IOS" >
		<modello>
			<nome> Iphone X </nome>
			<annoproduzione> 2019 </annoproduzione>
		</modello>
		<prezzo> 899 </prezzo>
		<componenti>
			<processore>
				<nome> Kirin 990 </nome>
				<frequenza> 1.6 Ghz </frequenza>
			</processore>
			<schedagrafica>
				<nome> Mali 880 </nome>
				<vram> 1 Gb </vram>
			</schedagrafica>
			<ram>
				<nome> Corsair </nome>
				<quantita> 4 Gb </quantita>
			</ram>
			<schedarete tecnologia=" 4G " >
				<nome> Atcp </nome>
			</schedarete>
			<display tipologia= "IPS">
				<dimensioni> 6 Pollici </dimensioni>
			</display>
		</componenti>
	</telefono>
	
	<telefono id="174" stato="IT" os= "Android" >
		<modello>
			<nome> Samsung s7</nome>
			<annoproduzione> 2016 </annoproduzione>
		</modello>
		<prezzo> 499 </prezzo>
		<componenti>
			<processore>
				<nome>Dragon 478 </nome>
				<frequenza> 1.2 Ghz </frequenza>
			</processore>
			<schedagrafica>
				<nome> Gtx880 </nome>
				<vram> 1 Gb </vram>
			</schedagrafica>
			<ram>
				<nome> Mediatech </nome>
				<quantita> 2 Gb </quantita>
			</ram>
			<schedarete tecnologia=" 3G " >
				<nome> Atcp </nome>
			</schedarete>
			<display tipologia= "OLED">
				<dimensioni> 5 Pollici </dimensioni>
			</display>
		</componenti>
	</telefono>
	
	<telefono id="199" stato="CH" os= "Android" >
		<modello>
			<nome> Samsung s20 </nome>
			<annoproduzione> 2020 </annoproduzione>
		</modello>
		<prezzo> 799 </prezzo>
		<componenti>
			<processore>
				<nome> Hexynos </nome>
				<frequenza> 2 Ghz </frequenza>
			</processore>
			<schedagrafica>
				<nome> Andriks 80 </nome>
				<vram> 1.6 Gb </vram>
			</schedagrafica>
			<ram>
				<nome> Pollis </nome>
				<quantita> 8 Gb </quantita>
			</ram>
			<schedarete tecnologia="5G">
				<nome> Seba</nome>
			</schedarete>
			<display tipologia= "AMOLED">
				<dimensioni> 6.2 pollici </dimensioni>
			</display>
		</componenti>
	</telefono>
	
	<telefono id="122" stato="FR" os= "IOS" >
		<modello>
			<nome> Iphone 11</nome>
			<annoproduzione> 2021 </annoproduzione>
		</modello>
		<prezzo> 1099 </prezzo>
		<componenti>
			<processore>
				<nome> Kirin 1000 </nome>
				<frequenza> 2 Ghz </frequenza>
			</processore>
			<schedagrafica>
				<nome> Mali 880 </nome>
				<vram> 2 Gb </vram>
			</schedagrafica>
			<ram>
				<nome> Corsair </nome>
				<quantita> 6 Gb </quantita>
			</ram>
			<schedarete tecnologia=" 5G " >
				<nome> Atcp </nome>
			</schedarete>
			<display tipologia= "AMOLED">
				<dimensioni> 6 Pollici </dimensioni>
			</display>
		</componenti>
	</telefono>
	
</telefoni>
